spring:
  application:
    name: aiservice
  data:
    mongodb:
      uri: mongodb://localhost:27017/activityfitness
      database: recommendations

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8097